apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
        containers:
        - name: order-service
          image: order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh","-c","sleep 5"]
          ports:
            - containerPort: 9005
          env:
          - name: POLAR_CATALOG_SERVICE_URI
            value: http://catalog-service
          - name: SPRING_CLOUD_CONFIG_URI
            value: http://config-service
          - name: SPRING_R2DBC_URL
            value: r2dbc:postgresql://polar-postgres/polardb_order
          - name: SPRING_R2DBC_USERNAME
            value: user
          - name: SPRING_R2DBC_PASSWORD
            value: password
          - name: SPRING_FLYWAY_URL
            value: jdbc:postgresql://polar-postgres/polardb_order
          - name: SPRING_FLYWAY_USER
            value: user
          - name: SPRING_FLYWAY_PASSWORD
            value: password
          - name: SERVER_PORT
            value: "9005"


